import { GRAPH_VERSION } from "./core.mjs";
import { summarize } from "./validate.mjs";
import { edgeStats } from "./relations.mjs";

const ENTRY_POINTS = [
  "app/_layout.tsx",
  "app/tabs/_layout.tsx",
  "src/components/index.ts",
  "src/bridge/index.ts",
  "backend/src/index.ts",
];

function inboundCount(graph, id, edgeType) {
  return graph.edges.filter(
    (e) => e.target === id && (!edgeType || e.type === edgeType)
  ).length;
}

function outboundCount(graph, id) {
  return graph.edges.filter((e) => e.source === id).length;
}

function groupRoutes(graph) {
  const app = [];
  const backend = [];
  for (const n of graph.nodes) {
    if (n.type !== "route") continue;
    const entry = { id: n.id, inbound: inboundCount(graph, n.id) };
    if (n.id.startsWith("backend/") || n.id.startsWith("api/")) backend.push(entry);
    else app.push(entry);
  }
  app.sort((a, b) => a.id.localeCompare(b.id));
  backend.sort((a, b) => a.id.localeCompare(b.id));
  return { app, backend };
}

function topComponents(graph) {
  const counts = new Map();
  for (const e of graph.edges) {
    if (e.type !== "uses") continue;
    counts.set(e.target, (counts.get(e.target) || 0) + 1);
  }
  const rows = [];
  for (const n of graph.nodes) {
    if (n.type !== "source") continue;
    if (!n.id.startsWith("src/components/")) continue;
    rows.push({ id: n.id, uses: counts.get(n.id) || 0 });
  }
  rows.sort((a, b) => b.uses - a.uses || a.id.localeCompare(b.id));
  return rows.slice(0, 15);
}

function findingsTable(validation) {
  const all = [...validation.errors.map((f) => ({ ...f, _sev: "error" })), ...validation.warnings.map((f) => ({ ...f, _sev: "warning" }))];
  const byCode = new Map();
  for (const f of all) {
    if (!byCode.has(f.code)) byCode.set(f.code, { code: f.code, severity: "error", count: 0, examples: [] });
    const bucket = byCode.get(f.code);
    bucket.count += 1;
    if (f._sev === "error") bucket.severity = "error";
    else if (bucket.severity !== "error") bucket.severity = "warning";
    if (bucket.examples.length < 3) bucket.examples.push(f.message);
  }
  const codes = [...byCode.keys()].sort();
  const lines = [];
  if (codes.length === 0) {
    lines.push("_No findings._");
    return lines;
  }
  lines.push("| Code | Severity | Count | Example messages |");
  lines.push("| ---- | -------- | ----- | ---------------- |");
  for (const code of codes) {
    const b = byCode.get(code);
    const examples = b.examples.map((m) => "`" + m.replace(/\|/g, "\\|") + "`").join("<br>");
    lines.push(`| ${b.code} | ${b.severity} | ${b.count} | ${examples} |`);
  }
  return lines;
}

export function generateArchitectureDoc(graph, validation, root) {
  const summary = summarize(validation);
  const stats = edgeStats(graph);
  const lines = [];

  lines.push("# OpenBand Architecture (auto-generated)");
  lines.push("");
  lines.push(`> Generated by Graph Engineer V3 on ${new Date().toISOString()}. Graph schema version ${GRAPH_VERSION}.`);
  lines.push("> This file is auto-generated — do not edit by hand. Regenerate with `npm run graph:doc`.");
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Nodes:** ${stats.nodes}`);
  lines.push(`- **Edges:** ${stats.edges}`);
  lines.push(`- **Validation:** ${summary.valid ? "PASS" : "FAIL"} (${summary.errors} errors, ${summary.warnings} warnings)`);
  lines.push("");
  lines.push("### Edges by type");
  lines.push("");
  lines.push("| Type | Count |");
  lines.push("| ---- | ----- |");
  const types = Object.keys(stats.byType).sort();
  for (const t of types) lines.push(`| ${t} | ${stats.byType[t]} |`);
  lines.push("");

  lines.push("## Entry points");
  lines.push("");
  const present = ENTRY_POINTS.filter((id) => graph.nodes.some((n) => n.id === id));
  if (present.length === 0) lines.push("_None of the known entry points are present._");
  else for (const id of present) lines.push(`- \`${id}\``);
  lines.push("");

  lines.push("## Routes");
  lines.push("");
  const { app, backend } = groupRoutes(graph);
  lines.push(`### App routes (${app.length})`);
  lines.push("");
  if (app.length === 0) lines.push("_None._");
  else for (const r of app) lines.push(`- \`${r.id}\` — ${r.inbound} inbound edge(s)`);
  lines.push("");
  lines.push(`### Backend routes (${backend.length})`);
  lines.push("");
  if (backend.length === 0) lines.push("_None._");
  else for (const r of backend) lines.push(`- \`${r.id}\` — ${r.inbound} inbound edge(s)`);
  lines.push("");

  lines.push("## Top components");
  lines.push("");
  lines.push("Most-reused components under `src/components/` by inbound `uses` edge count (top 15):");
  lines.push("");
  const top = topComponents(graph);
  if (top.length === 0) lines.push("_No components found._");
  else {
    lines.push("| Component | Used by |");
    lines.push("| -------- | ------- |");
    for (const c of top) lines.push(`| \`${c.id}\` | ${c.uses} |`);
  }
  lines.push("");

  lines.push("## Validation findings");
  lines.push("");
  lines.push(`Status: **${summary.valid ? "PASS" : "FAIL"}** (${summary.errors} errors, ${summary.warnings} warnings).`);
  lines.push("");
  lines.push(...findingsTable(validation));
  lines.push("");

  lines.push("## Regenerate");
  lines.push("");
  lines.push("```bash");
  lines.push("npm run graph:doc      # writes docs/generated/ARCHITECTURE.md");
  lines.push("npm run graph:report    # writes .openband/graph-report.html");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

export { ENTRY_POINTS, inboundCount, outboundCount };
