import { renderSubgraph } from "./render.mjs";
import { summarize } from "./validate.mjs";

const DOC_START = `<!doctype html>`;

function escapeHtml(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function degrees(graph) {
  const inDeg = new Map();
  const outDeg = new Map();
  for (const n of graph.nodes) {
    inDeg.set(n.id, 0);
    outDeg.set(n.id, 0);
  }
  for (const e of graph.edges) {
    outDeg.set(e.source, (outDeg.get(e.source) || 0) + 1);
    inDeg.set(e.target, (inDeg.get(e.target) || 0) + 1);
  }
  return { inDeg, outDeg };
}

function nodeRows(graph, inDeg, outDeg) {
  const rows = graph.nodes
    .map((n) => ({ id: n.id, type: n.type, in: inDeg.get(n.id) || 0, out: outDeg.get(n.id) || 0 }))
    .sort((a, b) => a.id.localeCompare(b.id));
  return rows
    .map(
      (r) =>
        `<tr data-id="${escapeHtml(r.id)}"><td>${escapeHtml(r.id)}</td><td>${escapeHtml(r.type)}</td><td>${r.in}</td><td>${r.out}</td></tr>`
    )
    .join("\n");
}

function validationRows(validation) {
  const all = [...validation.errors.map((f) => ({ ...f, severity: "error" })), ...validation.warnings.map((f) => ({ ...f, severity: "warning" }))];
  all.sort((a, b) => a.code.localeCompare(b.code));
  if (all.length === 0) return `<tr><td colspan="3" class="ok">No findings</td></tr>`;
  return all
    .map(
      (f) =>
        `<tr class="sev-${f.severity}"><td>${escapeHtml(f.code)}</td><td>${f.severity}</td><td>${escapeHtml(f.message)}</td></tr>`
    )
    .join("\n");
}

export function generateHtmlReport(graph, validation, { root } = {}) {
  const summary = summarize(validation);
  const { inDeg, outDeg } = degrees(graph);
  const entryNode = graph.nodes.find((n) => n.id === "app/_layout.tsx");
  const mermaidBlock = entryNode
    ? `<pre class="mermaid">${escapeHtml(renderSubgraph(graph, "app/_layout.tsx", { depth: 1, format: "mermaid" }))}</pre>`
    : "";

  const data = JSON.stringify({ nodes: graph.nodes, edges: graph.edges, validation }).replace(/</g, "\\u003c");

  const html = `${DOC_START}
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>OpenBand Architecture Report</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; background: #0d1117; color: #e6edf3; font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; }
  header { padding: 20px 24px; border-bottom: 1px solid #21262d; background: #161b22; }
  header h1 { margin: 0 0 4px; font-size: 20px; }
  header p { margin: 0; color: #8b949e; font-size: 13px; }
  main { padding: 20px 24px; max-width: 1100px; margin: 0 auto; }
  section { margin-bottom: 28px; }
  h2 { font-size: 16px; border-bottom: 1px solid #21262d; padding-bottom: 6px; }
  .status-pass { color: #3fb950; font-weight: 600; }
  .status-fail { color: #f85149; font-weight: 600; }
  .stats { display: flex; gap: 16px; flex-wrap: wrap; }
  .stat { background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 12px 16px; min-width: 110px; }
  .stat .v { font-size: 22px; font-weight: 700; }
  .stat .k { font-size: 12px; color: #8b949e; }
  input#q { width: 100%; box-sizing: border-box; padding: 10px 12px; background: #0d1117; border: 1px solid #30363d; border-radius: 8px; color: #e6edf3; font-size: 14px; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }
  th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #21262d; }
  th { color: #8b949e; font-weight: 600; position: sticky; top: 0; background: #0d1117; }
  tbody tr:hover { background: #161b22; cursor: pointer; }
  tr.sev-error td { color: #ff7b72; }
  tr.sev-warning td { color: #d29922; }
  td.ok { color: #3fb950; }
  pre.mermaid { background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 14px; overflow: auto; }
  #detail { background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 14px; display: none; }
  #detail h3 { margin: 0 0 8px; font-size: 14px; }
  #detail ul { margin: 4px 0; padding-left: 18px; }
  .pill { display: inline-block; font-size: 11px; padding: 2px 8px; border-radius: 999px; background: #21262d; color: #8b949e; }
</style>
</head>
<body>
<header>
  <h1>OpenBand Architecture Report</h1>
  <p>Auto-generated by Graph Engineer V3 &middot; schema ${escapeHtml(graph.version || "")} &middot; validation ${summary.valid ? '<span class="status-pass">PASS</span>' : '<span class="status-fail">FAIL</span>'}</p>
</header>
<main>
  <section>
    <h2>Summary</h2>
    <div class="stats">
      <div class="stat"><div class="v">${graph.nodes.length}</div><div class="k">Nodes</div></div>
      <div class="stat"><div class="v">${graph.edges.length}</div><div class="k">Edges</div></div>
      <div class="stat"><div class="v">${summary.errors}</div><div class="k">Errors</div></div>
      <div class="stat"><div class="v">${summary.warnings}</div><div class="k">Warnings</div></div>
    </div>
  </section>
  ${mermaidBlock ? `<section><h2>Entry-point neighborhood</h2>${mermaidBlock}</section>` : ""}
  <section>
    <h2>Nodes</h2>
    <input id="q" placeholder="Filter by id substring..." />
    <table id="nodes">
      <thead><tr><th>id</th><th>type</th><th>in</th><th>out</th></tr></thead>
      <tbody>
${nodeRows(graph, inDeg, outDeg)}
      </tbody>
    </table>
  </section>
  <section>
    <h2>Node detail</h2>
    <div id="detail"></div>
  </section>
  <section>
    <h2>Validation findings</h2>
    <table id="validation">
      <thead><tr><th>code</th><th>severity</th><th>message</th></tr></thead>
      <tbody>
${validationRows(validation)}
      </tbody>
    </table>
  </section>
</main>
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({ startOnLoad: true });</script>
<script id="graph-data" type="application/json">${data}</script>
<script>
(function () {
  const data = JSON.parse(document.getElementById("graph-data").textContent);
  const adjFwd = new Map();
  const adjBwd = new Map();
  for (const e of data.edges) {
    if (!adjFwd.has(e.source)) adjFwd.set(e.source, []);
    if (!adjBwd.has(e.target)) adjBwd.set(e.target, []);
    adjFwd.get(e.source).push(e.target);
    adjBwd.get(e.target).push(e.source);
  }
  const q = document.getElementById("q");
  const rows = Array.from(document.querySelectorAll("#nodes tbody tr"));
  q.addEventListener("input", function () {
    const term = q.value.trim().toLowerCase();
    for (const tr of rows) {
      const id = (tr.getAttribute("data-id") || "").toLowerCase();
      tr.style.display = !term || id.includes(term) ? "" : "none";
    }
  });
  const detail = document.getElementById("detail");
  function renderDetail(id) {
    const deps = adjFwd.get(id) || [];
    const depsOn = adjBwd.get(id) || [];
    detail.style.display = "block";
    detail.innerHTML = "";
    const h = document.createElement("h3");
    h.textContent = id;
    detail.appendChild(h);
    const mk = (label, list) => {
      const p = document.createElement("div");
      const s = document.createElement("span");
      s.className = "pill";
      s.textContent = label + " (" + list.length + ")";
      p.appendChild(s);
      const ul = document.createElement("ul");
      if (list.length === 0) {
        const li = document.createElement("li");
        li.textContent = "none";
        ul.appendChild(li);
      } else {
        for (const t of list) {
          const li = document.createElement("li");
          li.textContent = t;
          ul.appendChild(li);
        }
      }
      p.appendChild(ul);
      detail.appendChild(p);
    };
    mk("Depends on", deps);
    mk("Depended on by", depsOn);
  }
  for (const tr of rows) {
    tr.addEventListener("click", function () {
      renderDetail(tr.getAttribute("data-id"));
      detail.scrollIntoView({ behavior: "smooth" });
    });
  }
})();
</script>
</body>
</html>
`;
  return html;
}
